server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/estudiantes_db;DB_CLOSE_DELAY=-1;
    username: root
    password: root
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
