server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: estudianteRoute #Identificando la ruta del service de producto
          uri: http://localhost:8081/ #URL donde se hará el redirect segun el predicate definido
          predicates: #RReglas de análisis de una request
            - Path=/estudiantes/**
        - id: materiaRoute #Identificando la ruta del service de producto
          uri: http://localhost:8082/ #URL donde se hará el redirect segun el predicate definido
          predicates: #RReglas de análisis de una request
            - Path=/materias/**
        - id: cursadaRoute #Identificando la ruta del service de producto
          uri: http://localhost:8083/ #URL donde se hará el redirect segun el predicate definido
          predicates: #RReglas de análisis de una request
            - Path=/cursadas/**
